package gtf.math.algebra;


/**
 * A finite-dimensional Clifford (geometric) algebra.
 *
 * <p>
 * The algebra is generated by a finite-dimensional inner-product space using
 * the geometric product.
 * </p>
 *
 * @author gtf
 *
 * @param <V> the type of the underlying vector-space elements
 * @param <S> the type of the scalar-field elements
 * @param <F> the scalar field
 */
public interface CliffordAlgebra<V, S, F extends Field<S>> {

  /**
   * @return the underlying inner-product space
   */
  InnerProductSpace<V, S, F> vectorSpace();

  /**
   * Computes the geometric product of two multivectors.
   *
   * @param a the first multivector
   * @param b the second multivector
   * @return the geometric product
   */
  Multivector<S, F> geometricProduct(
      Multivector<S, F> a,
      Multivector<S, F> b);

  /**
   * Computes the exterior (wedge) product of two multivectors.
   *
   * @param a the first multivector
   * @param b the second multivector
   * @return the wedge product
   */
  Multivector<S, F> wedge(
      Multivector<S, F> a,
      Multivector<S, F> b);

  /**
   * Computes the inner product of two multivectors.
   *
   * @param a the first multivector
   * @param b the second multivector
   * @return the inner product
   */
  Multivector<S, F> innerProduct(
      Multivector<S, F> a,
      Multivector<S, F> b);

  /**
   * Computes the Hodge dual of a multivector relative to the distinguished
   * oriented orthonormal basis.
   *
   * @param a the multivector
   * @return the Hodge dual
   */
  Multivector<S, F> hodgeDual(Multivector<S, F> a);

  /**
   * Computes the three-dimensional vector cross product as the Hodge dual of
   * the wedge product.
   *
   * @param a the first vector, represented as a grade-1 multivector
   * @param b the second vector, represented as a grade-1 multivector
   * @return the cross product, represented as a grade-1 multivector
   */
  Multivector<S, F> crossProduct(
      Multivector<S, F> a,
      Multivector<S, F> b);
}
