package gtf.math.algebra;

import gtf.math.algebra.impl.ArrayMultivector;


/**
 * A finite-dimensional Clifford (geometric) algebra.
 *
 * <p>
 * The algebra is generated by a finite-dimensional inner-product space using
 * the geometric product. This class currently provides blade-grade utilities,
 * the exterior (wedge) product, Hodge dual, and the three-dimensional vector
 * cross product.
 * </p>
 *
 * @author gtf
 *
 * @param <V> the type of the underlying vector-space elements
 * @param <S> the type of the scalar-field elements
 * @param <F> the scalar field
 */
public class CliffordAlgebra<V, S, F extends Field<S>> {

  private final InnerProductSpace<V, S, F> vectorSpace;

  public CliffordAlgebra(InnerProductSpace<V, S, F> vectorSpace) {
    if (vectorSpace == null) {
      throw new NullPointerException("vectorSpace");
    }
    this.vectorSpace = vectorSpace;
  }

  /**
   * @return the underlying inner-product space
   */
  public InnerProductSpace<V, S, F> vectorSpace() {
    return vectorSpace;
  }

  /**
   * Returns the grade of a basis blade.
   *
   * @param blade the blade bit mask
   * @return the blade grade
   */
  public int grade(int blade) {
    return Integer.bitCount(blade);
  }

  /**
   * Computes the exterior (wedge) product of two multivectors.
   *
   * @param a the first multivector
   * @param b the second multivector
   * @return the wedge product
   */
  public Multivector<S, F> wedge(
      Multivector<S, F> a,
      Multivector<S, F> b) {

    validateCompatible(a, b);

    F field = a.field();
    ArrayMultivector<S, F> result =
        new ArrayMultivector<S, F>(field, a.dimension());

    for (int bladeA = 0; bladeA < a.bladeCount(); bladeA++) {
      S coeffA = a.coefficient(bladeA);

      for (int bladeB = 0; bladeB < b.bladeCount(); bladeB++) {
        S coeffB = b.coefficient(bladeB);

        if ((bladeA & bladeB) != 0) {
          continue;
        }

        int blade = bladeA ^ bladeB;

        S term = field.mul(coeffA, coeffB);

        if (swapParity(bladeA, bladeB)) {
          term = field.neg(term);
        }

        result.setCoefficient(blade,
            field.add(result.coefficient(blade), term));
      }
    }

    return result;
  }

  /**
   * Computes the Hodge dual of a multivector relative to the distinguished
   * oriented orthonormal basis.
   *
   * @param a the multivector
   * @return the Hodge dual
   */
  public Multivector<S, F> hodgeDual(Multivector<S, F> a) {

    F field = a.field();
    int pseudoscalar = (1 << a.dimension()) - 1;

    ArrayMultivector<S, F> result =
        new ArrayMultivector<S, F>(field, a.dimension());

    for (int blade = 0; blade < a.bladeCount(); blade++) {
      int dualBlade = pseudoscalar ^ blade;

      S coeff = a.coefficient(blade);

      if (swapParity(blade, dualBlade)) {
        coeff = field.neg(coeff);
      }

      result.setCoefficient(dualBlade,
          field.add(result.coefficient(dualBlade), coeff));
    }

    return result;
  }

  /**
   * Computes the three-dimensional vector cross product as the Hodge dual of
   * the wedge product.
   *
   * @param a the first vector, represented as a grade-1 multivector
   * @param b the second vector, represented as a grade-1 multivector
   * @return the cross product, represented as a grade-1 multivector
   */
  public Multivector<S, F> crossProduct(
      Multivector<S, F> a,
      Multivector<S, F> b) {

    if (a.dimension() != 3 || b.dimension() != 3) {
      throw new IllegalArgumentException(
          "cross product is only defined in dimension 3");
    }

    return hodgeDual(wedge(a, b));
  }

  /**
   * Computes the geometric product of two multivectors.
   *
   * @param a the first multivector
   * @param b the second multivector
   * @return the geometric product
   */
  public Multivector<S, F> geometricProduct(
      Multivector<S, F> a,
      Multivector<S, F> b) {

    throw new UnsupportedOperationException(
        "geometric product not implemented yet");
  }

  /**
   * Computes the inner product of two multivectors.
   *
   * @param a the first multivector
   * @param b the second multivector
   * @return the inner product
   */
  public Multivector<S, F> innerProduct(
      Multivector<S, F> a,
      Multivector<S, F> b) {

    throw new UnsupportedOperationException(
        "multivector inner product not implemented yet");
  }

  private void validateCompatible(
      Multivector<S, F> a,
      Multivector<S, F> b) {

    if (a.dimension() != b.dimension()) {
      throw new IllegalArgumentException("dimension mismatch");
    }
  }

  /**
   * Returns true if the blade permutation has odd parity.
   */
  private boolean swapParity(int bladeA, int bladeB) {
    int swaps = 0;

    for (int i = 0; i < Integer.SIZE; i++) {
      if ((bladeA & (1 << i)) != 0) {
        swaps += Integer.bitCount(bladeB & ((1 << i) - 1));
      }
    }

    return (swaps & 1) != 0;
  }
}
